### ISSUE TITLE
Derivative w.r.t initial conditions with saveat for end point

### ISSUE THREAD

**Issue by martinwu42** [JuliaDiffEq/DiffEqFlux.jl#25]
Thanks a lot for your work! I wonder if it could support taking derivative w.r.t initial conditions, such as `u0 = param([1.0, 1.0])`, rather than `p = param([1.5, 1.0, 3.0, 1.0])`.

Today I noticed that the code in `README.md` cannot run properly because of some update of upstream packages, so I cannot make an example of taking derivative w.r.t initial conditions now. Last time I tried it, it throws error.

**Comment by ChrisRackauckas** [comment]
This was recently added, but then DiffEq v6.0's big update came out which caused a bit of havoc here. We are looking over this in the next few days.

**Comment by ChrisRackauckas** [comment]
This should work now. Let me know if you run into any issues.

**Comment by martinwu42** [comment]
Hi, Chris. It seems that the derivative w.r.t initial conditions is still not working. In the following code, `grad_ode(x)` and `grads[x]` just give all `1.0`.

```julia
using DiffEqFlux
using DifferentialEquations
using Flux
using Flux.Tracker

const N = 4

net = Chain(Dense(N, N, relu), Dense(N, N))
tspan = (0.0, 1.0)
ode(x) = neural_ode(net, x, tspan, Tsit5(), saveat = (tspan[2],), save_start = false)
grad_ode(x) = gradient(xx->sum(ode(xx)), x; nest = true)[1]

x = param(randn(Float32, N))
print(grad_ode(x))

grads = gradient(()->sum(ode(x)), params(x))
print(grads[x])
```

Environments:

```
Windows 10, Julia 1.1.1
[aae7a2af] DiffEqFlux v0.5.2
[0c46a032] DifferentialEquations v6.6.0
[587475ba] Flux v0.8.3
```

Sorry that I have been not following the development of DiffEqFlux for a long time. It has gone through many updates, and I didn't try if it works in the past. Thanks for your help!

**Comment by ChrisRackauckas** [comment]
`saveat` at only the final time is a little odd. The following code is more standard and works:

```julia
using DiffEqFlux
using DifferentialEquations
using Flux
using Flux.Tracker

const N = 4

net = Chain(Dense(N, N, relu), Dense(N, N))
tspan = (0.0, 1.0)
ode(x) = neural_ode(net, x, tspan, Tsit5(), save_everystep=false,save_start=false)
grad_ode(x) = gradient(xx->sum(ode(xx)), x; nest = true)[1]

x = param(randn(Float32, N))
print(grad_ode(x))

grads = gradient(()->sum(ode(x)), params(x))
print(grads[x])
```

I don't know why yours doesn't though... peculiar.

**Comment by martinwu42** [comment]
Thanks! It works now. That's really a subtle behavior.

**Comment by ChrisRackauckas** [comment]
Yeah, I'm re-opening the issue to find out why that occurs, but for now there is a workaround. The workaround is more standard way of writing that for DiffEq users, so this is not the highest priority, but I'd like to get it fixed anyways.

**Comment by martinwu42** [comment]
Today the code cannot work again. The error message is 

```
ERROR: MethodError: Cannot `convert` an object of type DataStructures.BinaryHeap{Float32,DataStructures.GreaterThan} to an object of type DataStructures.BinaryHeap{Float64,DataStructures.GreaterThan}
```

Environments:

```
Windows 10, Julia 1.1.1
[aae7a2af] DiffEqFlux v0.6.1
[0c46a032] DifferentialEquations v6.6.0
[587475ba] Flux v0.8.3
```

BTW, I'm doing research on physics+ML, where there are some complicated use of ODE and autodiff. such complicated operations seldom exist in 'ordinary' ML fields like CV, so there seems to be few developers aware of them. AFAIK, at present no ML framework can do `d^2 y / dx^2` where y is something like `sum(ode(x))`, with reasonable memory usage (adjoint or checkpoint). In physics, such operation is used to calculate the kinetic energy.

I'm willing to implement it by myself (only in spare times, as making computer wheels is not the major work in our physics department), and I feel Julia's concept of interoperating ODE and autodiff packages by multiple dispatch is really promising and eases the development. However, the huge amount of error message forbids me to debug, which reminds me of C++ STL templates. Maybe I would take some time to understand the codebases of DifferentialEquations.jl and Flux.jl. Anyway, thanks for your great work!

**Comment by ChrisRackauckas** [comment]
You accidentally made a Float64 value instead of a Float32 value in your setup. Check all of your things for Float64's. Any `1e0` should be `1f0`. Let me know when you find out what it is so I can try to intercept this with a better error message.

**Comment by martinwu42** [comment]
ok, I change to `tspan = (0f0, 1f0)` and it works. Thank you!

**Comment by devmotion** [comment]
For me, both alternatives work with the latest master of OrdinaryDiffEq. Maybe a side-effect of the latest changes in `tstop_saveat_disc_handling`?

**Comment by ChrisRackauckas** [comment]
Yeah, looks like it's fixed. That change in OrdinaryDiffEq fixed a lot of these small AD issues.
